services:
  server:
    image: sorokchat
    container_name: server
    build:
      context: .
      dockerfile: SorokChatServer.API/Dockerfile
    ports:
      - "80:8080"
  database: 
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sorokchat
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
    driver: local