// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SorokChatServer.Postgres;

#nullable disable

namespace SorokChatServer.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251116135708_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatEntityUserEntity", b =>
                {
                    b.Property<long>("ChatEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_entity_id");

                    b.Property<long>("MembersId")
                        .HasColumnType("bigint")
                        .HasColumnName("members_id");

                    b.HasKey("ChatEntityId", "MembersId")
                        .HasName("pk_chat_entity_user_entity");

                    b.HasIndex("MembersId")
                        .HasDatabaseName("ix_chat_entity_user_entity_members_id");

                    b.ToTable("chat_entity_user_entity", (string)null);
                });

            modelBuilder.Entity("SorokChatServer.Postgres.Entities.ChatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("SorokChatServer.Postgres.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long?>("ChatEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_entity_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mac");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_messages_author_id");

                    b.HasIndex("ChatEntityId")
                        .HasDatabaseName("ix_messages_chat_entity_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("SorokChatServer.Postgres.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MacSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mac_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ChatEntityUserEntity", b =>
                {
                    b.HasOne("SorokChatServer.Postgres.Entities.ChatEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_entity_user_entity_chats_chat_entity_id");

                    b.HasOne("SorokChatServer.Postgres.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_entity_user_entity_users_members_id");
                });

            modelBuilder.Entity("SorokChatServer.Postgres.Entities.ChatEntity", b =>
                {
                    b.OwnsOne("SorokChatServer.Logic.Models.Description", "Description", b1 =>
                        {
                            b1.Property<long>("ChatEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.HasKey("ChatEntityId");

                            b1.ToTable("chats");

                            b1.WithOwner()
                                .HasForeignKey("ChatEntityId")
                                .HasConstraintName("fk_chats_chats_id");
                        });

                    b.OwnsOne("SorokChatServer.Logic.Models.Title", "Title", b1 =>
                        {
                            b1.Property<long>("ChatEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("title");

                            b1.HasKey("ChatEntityId");

                            b1.ToTable("chats");

                            b1.WithOwner()
                                .HasForeignKey("ChatEntityId")
                                .HasConstraintName("fk_chats_chats_id");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("SorokChatServer.Postgres.Entities.MessageEntity", b =>
                {
                    b.HasOne("SorokChatServer.Postgres.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_author_id");

                    b.HasOne("SorokChatServer.Postgres.Entities.ChatEntity", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatEntityId")
                        .HasConstraintName("fk_messages_chats_chat_entity_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SorokChatServer.Postgres.Entities.UserEntity", b =>
                {
                    b.OwnsOne("SorokChatServer.Logic.Models.Email", "Email", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("email");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("SorokChatServer.Logic.Models.HashedPassword", "Password", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("SorokChatServer.Logic.Models.Name", "Name", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("middle_name");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("SorokChatServer.Postgres.Entities.ChatEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
