// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SorokChatServer.Persistence.Postgres;

#nullable disable

namespace SorokChatServer.Persistence.Postgres.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20251207122632_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SorokChatServer.Persistence.Postgres.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SorokChatServer.Persistence.Postgres.Entities.UserEntity", b =>
                {
                    b.OwnsOne("SorokChatServer.Domain.Models.Email", "Email", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("SorokChatServer.Domain.Models.FullName", "FullName", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasDefaultValue("")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasDefaultValue("")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasDefaultValue("")
                                .HasColumnName("middle_name");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("SorokChatServer.Domain.Models.HashedPassword", "HashedPassword", b1 =>
                        {
                            b1.Property<long>("UserEntityId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("password");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("HashedPassword")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
